module.exports = {
  extends: ['airbnb', 'prettier', 'prettier/react'],
  endOfLine: 'lf',
  insertPragma: false,
  jsxBracketSameLine: false,
  jsxSingleQuote: true,
  requirePragma: false,
  tabWidth: 2,
  useTabs: false,
  arrowParens: 'always',
  quotes: true,
  eslintIntegration: false,
  bracketSpacing: true,
  trailingComma: 'all',
  singleQuote: true,
  printWidth: 120,
  tslintIntegration: false,
  semi: false,
  'arrow-spacing': 0,
}
